### ISSUE TITLE
trashwiki login error

### ISSUE THREAD

**Issue by simison** [guaka/wiki.yt-public#18]
Got message via FB:

> Trashwiki: I am throwing a dumpster diving laptop party where my friends and I are updating different locations in Uppsala, Sweden
But I cannot seem to log in at all
It gives me this error: 
> "[470a6052cf4e4d82bfc273f7] 2019-06-04 14:40:47: Fatal exception of type "Wikimedia\Rdbms\DBQueryError"" and it seems to only work on mobile or on incognito on firefox. Also, it's impossible to log in or make a new account.

Cc @guaka

**Comment by guaka** [comment]
same for me
<img width="939" alt="image" src="https://user-images.githubusercontent.com/54728/58911896-cd979280-8710-11e9-8858-4ac94e58384d.png">

fixed with `cd htdocs/w; php maintenance/update.php trash`

**Comment by simison** [comment]
Nice, thanks!
